import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import merchantsRouter from "./merchants";
import plansRouter from "./plans";
import productsRouter from "./products";
import customersRouter from "./customers";
import transactionsRouter from "./transactions";
import paymentsRouter from "./payments";
import staffRouter from "./staff";
import staffAuthRouter from "./staff-auth";
import inventoryRouter from "./inventory";
import stockTakesRouter from "./stock-takes";
import dashboardRouter from "./dashboard";
import dashboardNotesRouter from "./dashboard-notes";
import smsSettingsRouter from "./sms-settings";
import appointmentsRouter from "./appointments";
import serviceJobsRouter from "./service-jobs";
import serviceJobLinesRouter from "./service-job-lines";
import storeCreditRouter from "./store-credit";
import deviceHistoryRouter from "./device-history";
import serviceJobChecklistRouter from "./service-job-checklist";
import loanerDevicesRouter from "./loaner-devices";
import serviceJobTimeRouter from "./service-job-time";
import partCompatibilityRouter from "./part-compatibility";
import tradeInsRouter from "./trade-ins";
import publicBookingRouter from "./public-booking";
import servicePlansRouter from "./service-plans";
import scheduledReportsRouter from "./scheduled-reports";
import locationsRouter from "./locations";
import productStockRouter from "./product-stock";
import brandsRouter from "./brands";
import suppliersRouter from "./suppliers";
import tagsRouter from "./tags";
import productTypesRouter from "./product-types";
import invoicesRouter from "./invoices";
import quotesRouter from "./quotes";
import salesSettingsRouter from "./sales-settings";
import integrationsRouter from "./integrations";
import customerFilesCloudRouter from "./customer-files-cloud";
import storageRouter from "./storage";
import loyaltyRouter from "./loyalty";
import serviceSettingsRouter from "./service-settings";
import portalRouter from "./portal";
import cashDrawerRouter from "./cash-drawer";
import parkedSalesRouter from "./parked-sales";
import purchaseOrdersRouter from "./purchase-orders";
import productBundlesRouter from "./product-bundles";
import discountsRouter from "./discounts";
import wastageRouter from "./wastage";
import priceTiersRouter from "./price-tiers";
import taxSettingsRouter from "./tax-settings";
import emailSettingsRouter from "./email-settings";
import formsRouter from "./forms";
import formSubmissionsRouter from "./form-submissions";
import laybysRouter from "./laybys";
import xeroRouter from "./xero";
import payrollRouter from "./payroll";
import marketingAutomationRouter from "./marketing-automation";
import feedbackRouter from "./feedback";
import camerasRouter from "./cameras";
import socialFeedRouter from "./social-feed";
import socialMediaRouter from "./social-media";
import floorPlanRouter from "./floor-plan";
import openaiRouter from "./openai";
import aiSettingsRouter from "./ai-settings";
import productRecallsRouter from "./product-recalls";
import productPreOrdersRouter from "./product-pre-orders";
import productReturnAuthsRouter from "./product-return-auths";
import posRegistersRouter from "./pos-registers";
import posSettingsRouter from "./pos-settings";
import laybySettingsRouter from "./layby-settings";
import kpiRouter from "./kpi";
import qrRouter from "./qr";
import emailTemplatesRouter from "./email-templates";
import emailCampaignsRouter from "./email-campaigns";
import smsTemplatesRouter from "./sms-templates";
import smsCampaignsRouter from "./sms-campaigns";
import landingPagesRouter from "./landing-pages";
import shortlinksRouter from "./shortlinks";
import onlineStoreRouter from "./online-store";
import shippingCarriersRouter from "./shipping-carriers";
import marketplaceConnectionsRouter from "./marketplace-connections";
import deliveryOrdersRouter from "./delivery-orders";
import giftCardsRouter from "./gift-cards";
import posRegisterSessionsRouter from "./pos-register-sessions";
import posFavouritesRouter from "./pos-favourites";
import posStaffSessionsRouter from "./pos-staff-sessions";
import posTemplatesRouter from "./pos-templates";
import posReceiptSettingsRouter from "./pos-receipt-settings";
import posCodePrefixesRouter from "./pos-code-prefixes";
import inventorySettingsRouter from "./inventory-settings";
import lowStockAlertsRouter from "./low-stock-alerts";
import regionalExtSettingsRouter from "./regional-ext-settings";
import staffRosteringSettingsRouter from "./staff-rostering-settings";
import rosterRouter from "./roster";
import staffLinksRouter from "./staff-links";
import serviceJobTemplatesRouter from "./service-job-templates";
import marketingGeneratorsRouter from "./marketing-generators";
import salesTemplatesRouter from "./sales-templates";
import reportsRouter from "./reports";
import pcBuilderSettingsRouter from "./pc-builder-settings";
import pcSavedBuildsRouter from "./pc-saved-builds";
import pcCompatRulesRouter from "./pc-compat-rules";
import staffNotesRouter from "./staff-notes";
import print3dSettingsRouter from "./print-3d-settings";
import businessProfileRouter from "./business-profile";
import customerSettingsRouter from "./customer-settings";
import referralDigestRouter from "./referral-digest";
import stickerTemplatesRouter from "./sticker-templates";
import signaturesRouter from "./signatures";
import vaultRouter from "./vault";
import dailyClosesRouter from "./daily-closes";
import voidAuditRouter from "./void-audit";
import pricingRulesRouter from "./pricing-rules";
import modifierGroupsRouter from "./modifier-groups";
import quickbooksRouter from "./quickbooks";
import authSecuritySettingsRouter from "./auth-security-settings";
import backupsRouter from "./backups";
import partnerReferralsRouter from "./partner-referrals";
import unsubscribeRouter from "./unsubscribe";
import staffTimesheetsRouter from "./staff-timesheets";
import tyroSettingsRouter from "./tyro-settings";
import demoDataRouter from "./demo-data";
import techRouter from "./tech";
import techAppAdminRouter from "./tech-app-admin";
import mobilePosRouter from "./mobile-pos";
import mobilePosAppAdminRouter from "./mobile-pos-app-admin";
import dashboardAppAdminRouter from "./dashboard-app-admin";
import dashboardAppPublicRouter from "./dashboard-app-public";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(merchantsRouter);
router.use(plansRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(transactionsRouter);
router.use(paymentsRouter);
router.use(staffRouter);
router.use(staffAuthRouter);
router.use(inventoryRouter);
router.use(stockTakesRouter);
router.use(dashboardRouter);
router.use(dashboardNotesRouter);
router.use(smsSettingsRouter);
router.use(appointmentsRouter);
router.use(serviceJobsRouter);
router.use(serviceJobLinesRouter);
router.use(storeCreditRouter);
router.use(deviceHistoryRouter);
router.use(serviceJobChecklistRouter);
router.use(loanerDevicesRouter);
router.use(serviceJobTimeRouter);
router.use(partCompatibilityRouter);
router.use(tradeInsRouter);
router.use(publicBookingRouter);
router.use(servicePlansRouter);
router.use(scheduledReportsRouter);
router.use(locationsRouter);
router.use(productStockRouter);
router.use(brandsRouter);
router.use(suppliersRouter);
router.use(tagsRouter);
router.use(productTypesRouter);
router.use(invoicesRouter);
router.use(quotesRouter);
router.use(salesSettingsRouter);
router.use(integrationsRouter);
router.use(customerFilesCloudRouter);
router.use(storageRouter);
router.use(loyaltyRouter);
router.use(serviceSettingsRouter);
router.use(portalRouter);
router.use(techRouter);
router.use(techAppAdminRouter);
router.use(mobilePosRouter);
router.use(mobilePosAppAdminRouter);
router.use(dashboardAppAdminRouter);
router.use(dashboardAppPublicRouter);
router.use(cashDrawerRouter);
router.use(parkedSalesRouter);
router.use(purchaseOrdersRouter);
router.use(productBundlesRouter);
router.use(discountsRouter);
router.use(wastageRouter);
router.use(priceTiersRouter);
router.use(taxSettingsRouter);
router.use(emailSettingsRouter);
router.use(formsRouter);
router.use(formSubmissionsRouter);
router.use(laybysRouter);
router.use(xeroRouter);
router.use(payrollRouter);
router.use(marketingAutomationRouter);
router.use(feedbackRouter);
router.use(landingPagesRouter);
router.use(camerasRouter);
router.use(socialFeedRouter);
router.use(socialMediaRouter);
router.use(floorPlanRouter);
router.use(openaiRouter);
router.use(aiSettingsRouter);
router.use(productRecallsRouter);
router.use(productPreOrdersRouter);
router.use(productReturnAuthsRouter);
router.use(posRegistersRouter);
router.use(posSettingsRouter);
router.use(laybySettingsRouter);
router.use(kpiRouter);
router.use(qrRouter);
router.use(emailTemplatesRouter);
router.use(emailCampaignsRouter);
router.use(smsTemplatesRouter);
router.use(smsCampaignsRouter);
router.use(shortlinksRouter);
router.use(onlineStoreRouter);
router.use(shippingCarriersRouter);
router.use(marketplaceConnectionsRouter);
router.use(deliveryOrdersRouter);
router.use(giftCardsRouter);
router.use(posRegisterSessionsRouter);
router.use(posFavouritesRouter);
router.use(posStaffSessionsRouter);
router.use(posTemplatesRouter);
router.use(posReceiptSettingsRouter);
router.use(posCodePrefixesRouter);
router.use(inventorySettingsRouter);
router.use(lowStockAlertsRouter);
router.use(regionalExtSettingsRouter);
router.use(staffRosteringSettingsRouter);
router.use(rosterRouter);
router.use(staffLinksRouter);
router.use(serviceJobTemplatesRouter);
router.use(marketingGeneratorsRouter);
router.use(salesTemplatesRouter);
router.use(reportsRouter);
router.use(pcBuilderSettingsRouter);
router.use(pcSavedBuildsRouter);
router.use(pcCompatRulesRouter);
router.use(staffNotesRouter);
router.use(print3dSettingsRouter);
router.use(businessProfileRouter);
router.use(customerSettingsRouter);
router.use(referralDigestRouter);
router.use(stickerTemplatesRouter);
router.use(signaturesRouter);
router.use(vaultRouter);
router.use(dailyClosesRouter);
router.use(voidAuditRouter);
router.use(pricingRulesRouter);
router.use(modifierGroupsRouter);
router.use(quickbooksRouter);
router.use(authSecuritySettingsRouter);
router.use(backupsRouter);
router.use(partnerReferralsRouter);
router.use(unsubscribeRouter);
router.use(staffTimesheetsRouter);
router.use(tyroSettingsRouter);
router.use(demoDataRouter);

export default router;
