import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import merchantsRouter from "./merchants";
import plansRouter from "./plans";
import productsRouter from "./products";
import customersRouter from "./customers";
import transactionsRouter from "./transactions";
import staffRouter from "./staff";
import inventoryRouter from "./inventory";
import dashboardRouter from "./dashboard";
import appointmentsRouter from "./appointments";
import serviceJobsRouter from "./service-jobs";
import brandsRouter from "./brands";
import suppliersRouter from "./suppliers";
import tagsRouter from "./tags";
import invoicesRouter from "./invoices";
import integrationsRouter from "./integrations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(merchantsRouter);
router.use(plansRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(transactionsRouter);
router.use(staffRouter);
router.use(inventoryRouter);
router.use(dashboardRouter);
router.use(appointmentsRouter);
router.use(serviceJobsRouter);
router.use(brandsRouter);
router.use(suppliersRouter);
router.use(tagsRouter);
router.use(invoicesRouter);
router.use(integrationsRouter);

export default router;
