import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import merchantsRouter from "./merchants";
import plansRouter from "./plans";
import productsRouter from "./products";
import customersRouter from "./customers";
import transactionsRouter from "./transactions";
import staffRouter from "./staff";
import inventoryRouter from "./inventory";
import dashboardRouter from "./dashboard";
import appointmentsRouter from "./appointments";
import serviceJobsRouter from "./service-jobs";
import brandsRouter from "./brands";
import suppliersRouter from "./suppliers";
import tagsRouter from "./tags";
import productTypesRouter from "./product-types";
import invoicesRouter from "./invoices";
import integrationsRouter from "./integrations";
import storageRouter from "./storage";
import loyaltyRouter from "./loyalty";
import portalRouter from "./portal";
import cashDrawerRouter from "./cash-drawer";
import parkedSalesRouter from "./parked-sales";
import purchaseOrdersRouter from "./purchase-orders";
import productBundlesRouter from "./product-bundles";
import discountsRouter from "./discounts";
import wastageRouter from "./wastage";
import priceTiersRouter from "./price-tiers";
import taxSettingsRouter from "./tax-settings";
import emailSettingsRouter from "./email-settings";
import formsRouter from "./forms";
import formSubmissionsRouter from "./form-submissions";
import laybysRouter from "./laybys";
import xeroRouter from "./xero";
import marketingAutomationRouter from "./marketing-automation";
import feedbackRouter from "./feedback";
import camerasRouter from "./cameras";
import socialFeedRouter from "./social-feed";
import floorPlanRouter from "./floor-plan";
import openaiRouter from "./openai";
import aiSettingsRouter from "./ai-settings";
import productRecallsRouter from "./product-recalls";
import productPreOrdersRouter from "./product-pre-orders";
import productReturnAuthsRouter from "./product-return-auths";
import posRegistersRouter from "./pos-registers";
import posSettingsRouter from "./pos-settings";
import laybySettingsRouter from "./layby-settings";
import kpiRouter from "./kpi";
import qrRouter from "./qr";
import emailTemplatesRouter from "./email-templates";
import emailCampaignsRouter from "./email-campaigns";
import landingPagesRouter from "./landing-pages";
import shortlinksRouter from "./shortlinks";
import onlineStoreRouter from "./online-store";
import shippingCarriersRouter from "./shipping-carriers";
import marketplaceConnectionsRouter from "./marketplace-connections";
import deliveryOrdersRouter from "./delivery-orders";
import giftCardsRouter from "./gift-cards";
import posRegisterSessionsRouter from "./pos-register-sessions";
import posFavouritesRouter from "./pos-favourites";
import posStaffSessionsRouter from "./pos-staff-sessions";
import posTemplatesRouter from "./pos-templates";
import posReceiptSettingsRouter from "./pos-receipt-settings";
import posCodePrefixesRouter from "./pos-code-prefixes";
import inventorySettingsRouter from "./inventory-settings";
import regionalExtSettingsRouter from "./regional-ext-settings";
import staffRosteringSettingsRouter from "./staff-rostering-settings";
import staffLinksRouter from "./staff-links";
import serviceJobTemplatesRouter from "./service-job-templates";
import marketingGeneratorsRouter from "./marketing-generators";
import salesTemplatesRouter from "./sales-templates";
import reportsRouter from "./reports";
import pcBuilderSettingsRouter from "./pc-builder-settings";
import pcCompatRulesRouter from "./pc-compat-rules";
import print3dSettingsRouter from "./print-3d-settings";
import businessProfileRouter from "./business-profile";
import customerSettingsRouter from "./customer-settings";
import referralDigestRouter from "./referral-digest";
import stickerTemplatesRouter from "./sticker-templates";
import signaturesRouter from "./signatures";
import vaultRouter from "./vault";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(merchantsRouter);
router.use(plansRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(transactionsRouter);
router.use(staffRouter);
router.use(inventoryRouter);
router.use(dashboardRouter);
router.use(appointmentsRouter);
router.use(serviceJobsRouter);
router.use(brandsRouter);
router.use(suppliersRouter);
router.use(tagsRouter);
router.use(productTypesRouter);
router.use(invoicesRouter);
router.use(integrationsRouter);
router.use(storageRouter);
router.use(loyaltyRouter);
router.use(portalRouter);
router.use(cashDrawerRouter);
router.use(parkedSalesRouter);
router.use(purchaseOrdersRouter);
router.use(productBundlesRouter);
router.use(discountsRouter);
router.use(wastageRouter);
router.use(priceTiersRouter);
router.use(taxSettingsRouter);
router.use(emailSettingsRouter);
router.use(formsRouter);
router.use(formSubmissionsRouter);
router.use(laybysRouter);
router.use(xeroRouter);
router.use(marketingAutomationRouter);
router.use(feedbackRouter);
router.use(landingPagesRouter);
router.use(camerasRouter);
router.use(socialFeedRouter);
router.use(floorPlanRouter);
router.use(openaiRouter);
router.use(aiSettingsRouter);
router.use(productRecallsRouter);
router.use(productPreOrdersRouter);
router.use(productReturnAuthsRouter);
router.use(posRegistersRouter);
router.use(posSettingsRouter);
router.use(laybySettingsRouter);
router.use(kpiRouter);
router.use(qrRouter);
router.use(emailTemplatesRouter);
router.use(emailCampaignsRouter);
router.use(shortlinksRouter);
router.use(onlineStoreRouter);
router.use(shippingCarriersRouter);
router.use(marketplaceConnectionsRouter);
router.use(deliveryOrdersRouter);
router.use(giftCardsRouter);
router.use(posRegisterSessionsRouter);
router.use(posFavouritesRouter);
router.use(posStaffSessionsRouter);
router.use(posTemplatesRouter);
router.use(posReceiptSettingsRouter);
router.use(posCodePrefixesRouter);
router.use(inventorySettingsRouter);
router.use(regionalExtSettingsRouter);
router.use(staffRosteringSettingsRouter);
router.use(staffLinksRouter);
router.use(serviceJobTemplatesRouter);
router.use(marketingGeneratorsRouter);
router.use(salesTemplatesRouter);
router.use(reportsRouter);
router.use(pcBuilderSettingsRouter);
router.use(pcCompatRulesRouter);
router.use(print3dSettingsRouter);
router.use(businessProfileRouter);
router.use(customerSettingsRouter);
router.use(referralDigestRouter);
router.use(stickerTemplatesRouter);
router.use(signaturesRouter);
router.use(vaultRouter);

export default router;
