/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * KoaPOS Payroll API. Provider-backed payroll (Xero Payroll first). This spec is
generated independently of the main openapi.yaml into an isolated client module
(generated-payroll) so it never disturbs the existing generated surface.

OAuth connect/callback endpoints are intentionally omitted — they are browser
redirects served by the API and navigated to directly from the UI.

 * OpenAPI spec version: 0.1.0
 */
export interface PayrollStatus {
  /** Server OAuth client credentials present */
  configured: boolean;
  connected: boolean;
  providerKey: string;
  region: string;
  /** @nullable */
  accountHandle?: string | null;
  /** @nullable */
  payCalendarId?: string | null;
  /** @nullable */
  lastSyncAt?: string | null;
}

/**
 * @nullable
 */
export type PayrollSettingsAccountMappings = {[key: string]: string} | null;

export interface PayrollSettings {
  providerKey: string;
  region: string;
  status: string;
  /** @nullable */
  payCalendarId?: string | null;
  /** @nullable */
  accountMappings?: PayrollSettingsAccountMappings;
  /** @nullable */
  lastSyncAt?: string | null;
}

/**
 * @nullable
 */
export type UpdatePayrollSettingsInputAccountMappings = {[key: string]: string} | null;

export interface UpdatePayrollSettingsInput {
  providerKey?: string;
  region?: string;
  /** @nullable */
  payCalendarId?: string | null;
  /** @nullable */
  accountMappings?: UpdatePayrollSettingsInputAccountMappings;
}

export interface PayrollSyncResult {
  synced: number;
  failed?: number;
  message: string;
}

export interface SyncTimesheetsInput {
  /** YYYY-MM-DD */
  periodStart: string;
  /** YYYY-MM-DD */
  periodEnd: string;
}

export interface SyncJournalInput {
  payRunId: number;
}

export interface CreatePayRunInput {
  periodStart: string;
  periodEnd: string;
  /** @nullable */
  paymentDate?: string | null;
}

export interface PayRun {
  id: number;
  providerPayRunId: string;
  periodStart: string;
  periodEnd: string;
  /** @nullable */
  paymentDate?: string | null;
  status: string;
  grossCents: number;
  paygCents: number;
  superCents: number;
  netCents: number;
  employeeCount: number;
  createdAt?: string;
}

export interface PayRunList {
  items: PayRun[];
}

export interface Payslip {
  id: number;
  payRunId: number;
  /** @nullable */
  staffId?: number | null;
  providerPayslipId: string;
  providerEmployeeId?: string;
  employeeName: string;
  grossCents: number;
  paygCents: number;
  superCents: number;
  netCents: number;
  /** @nullable */
  leaveAccruedHours?: string | null;
  /** @nullable */
  pdfRef?: string | null;
}

export interface PayRunDetail {
  payRun: PayRun;
  payslips: Payslip[];
}

export interface PayslipList {
  items: Payslip[];
}

export interface LeaveBalance {
  id: number;
  /** @nullable */
  staffId?: number | null;
  providerEmployeeId: string;
  employeeName: string;
  leaveType: string;
  leaveTypeName: string;
  balanceHours: string;
  /** @nullable */
  accruedHours?: string | null;
  /** @nullable */
  asAtDate?: string | null;
}

export interface LeaveBalanceList {
  items: LeaveBalance[];
}

export type ListPayslipsParams = {
payRunId?: number;
staffId?: number;
};

export type ListLeaveBalancesParams = {
staffId?: number;
};

