/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * KoaPOS Payroll API. Provider-backed payroll (Xero Payroll first). This spec is
generated independently of the main openapi.yaml into an isolated client module
(generated-payroll) so it never disturbs the existing generated surface.

OAuth connect/callback endpoints are intentionally omitted — they are browser
redirects served by the API and navigated to directly from the UI.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePayRunInput,
  LeaveBalanceList,
  ListLeaveBalancesParams,
  ListPayslipsParams,
  PayRun,
  PayRunDetail,
  PayRunList,
  PayrollSettings,
  PayrollStatus,
  PayrollSyncResult,
  PayslipList,
  SyncJournalInput,
  SyncTimesheetsInput,
  UpdatePayrollSettingsInput
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetPayrollStatusUrl = () => {




  return `/api/payroll/status`
}

/**
 * @summary Payroll provider connection status
 */
export const getPayrollStatus = async ( options?: RequestInit): Promise<PayrollStatus> => {

  return customFetch<PayrollStatus>(getGetPayrollStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPayrollStatusQueryKey = () => {
    return [
    `/api/payroll/status`
    ] as const;
    }


export const getGetPayrollStatusQueryOptions = <TData = Awaited<ReturnType<typeof getPayrollStatus>>, TError = ErrorType<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPayrollStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPayrollStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPayrollStatus>>> = ({ signal }) => getPayrollStatus({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPayrollStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPayrollStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getPayrollStatus>>>
export type GetPayrollStatusQueryError = ErrorType<void>


/**
 * @summary Payroll provider connection status
 */

export function useGetPayrollStatus<TData = Awaited<ReturnType<typeof getPayrollStatus>>, TError = ErrorType<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPayrollStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPayrollStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetPayrollSettingsUrl = () => {




  return `/api/payroll/settings`
}

/**
 * @summary Get payroll settings
 */
export const getPayrollSettings = async ( options?: RequestInit): Promise<PayrollSettings> => {

  return customFetch<PayrollSettings>(getGetPayrollSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPayrollSettingsQueryKey = () => {
    return [
    `/api/payroll/settings`
    ] as const;
    }


export const getGetPayrollSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getPayrollSettings>>, TError = ErrorType<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPayrollSettings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPayrollSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPayrollSettings>>> = ({ signal }) => getPayrollSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPayrollSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPayrollSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getPayrollSettings>>>
export type GetPayrollSettingsQueryError = ErrorType<void>


/**
 * @summary Get payroll settings
 */

export function useGetPayrollSettings<TData = Awaited<ReturnType<typeof getPayrollSettings>>, TError = ErrorType<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPayrollSettings>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPayrollSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdatePayrollSettingsUrl = () => {




  return `/api/payroll/settings`
}

/**
 * @summary Update payroll settings
 */
export const updatePayrollSettings = async (updatePayrollSettingsInput: UpdatePayrollSettingsInput, options?: RequestInit): Promise<PayrollSettings> => {

  return customFetch<PayrollSettings>(getUpdatePayrollSettingsUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePayrollSettingsInput,)
  }
);}




export const getUpdatePayrollSettingsMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePayrollSettings>>, TError,{data: BodyType<UpdatePayrollSettingsInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePayrollSettings>>, TError,{data: BodyType<UpdatePayrollSettingsInput>}, TContext> => {

const mutationKey = ['updatePayrollSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePayrollSettings>>, {data: BodyType<UpdatePayrollSettingsInput>}> = (props) => {
          const {data} = props ?? {};

          return  updatePayrollSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePayrollSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof updatePayrollSettings>>>
    export type UpdatePayrollSettingsMutationBody = BodyType<UpdatePayrollSettingsInput>
    export type UpdatePayrollSettingsMutationError = ErrorType<void>

    /**
 * @summary Update payroll settings
 */
export const useUpdatePayrollSettings = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePayrollSettings>>, TError,{data: BodyType<UpdatePayrollSettingsInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updatePayrollSettings>>,
        TError,
        {data: BodyType<UpdatePayrollSettingsInput>},
        TContext
      > => {
      return useMutation(getUpdatePayrollSettingsMutationOptions(options));
    }

export const getSyncPayrollEmployeesUrl = () => {




  return `/api/payroll/sync/employees`
}

/**
 * @summary Sync staff to provider employees
 */
export const syncPayrollEmployees = async ( options?: RequestInit): Promise<PayrollSyncResult> => {

  return customFetch<PayrollSyncResult>(getSyncPayrollEmployeesUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getSyncPayrollEmployeesMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPayrollEmployees>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof syncPayrollEmployees>>, TError,void, TContext> => {

const mutationKey = ['syncPayrollEmployees'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncPayrollEmployees>>, void> = () => {


          return  syncPayrollEmployees(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncPayrollEmployeesMutationResult = NonNullable<Awaited<ReturnType<typeof syncPayrollEmployees>>>

    export type SyncPayrollEmployeesMutationError = ErrorType<void>

    /**
 * @summary Sync staff to provider employees
 */
export const useSyncPayrollEmployees = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPayrollEmployees>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof syncPayrollEmployees>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSyncPayrollEmployeesMutationOptions(options));
    }

export const getSyncPayrollTimesheetsUrl = () => {




  return `/api/payroll/sync/timesheets`
}

/**
 * @summary Push timesheets for a period to the provider
 */
export const syncPayrollTimesheets = async (syncTimesheetsInput: SyncTimesheetsInput, options?: RequestInit): Promise<PayrollSyncResult> => {

  return customFetch<PayrollSyncResult>(getSyncPayrollTimesheetsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncTimesheetsInput,)
  }
);}




export const getSyncPayrollTimesheetsMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPayrollTimesheets>>, TError,{data: BodyType<SyncTimesheetsInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof syncPayrollTimesheets>>, TError,{data: BodyType<SyncTimesheetsInput>}, TContext> => {

const mutationKey = ['syncPayrollTimesheets'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncPayrollTimesheets>>, {data: BodyType<SyncTimesheetsInput>}> = (props) => {
          const {data} = props ?? {};

          return  syncPayrollTimesheets(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncPayrollTimesheetsMutationResult = NonNullable<Awaited<ReturnType<typeof syncPayrollTimesheets>>>
    export type SyncPayrollTimesheetsMutationBody = BodyType<SyncTimesheetsInput>
    export type SyncPayrollTimesheetsMutationError = ErrorType<void>

    /**
 * @summary Push timesheets for a period to the provider
 */
export const useSyncPayrollTimesheets = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPayrollTimesheets>>, TError,{data: BodyType<SyncTimesheetsInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof syncPayrollTimesheets>>,
        TError,
        {data: BodyType<SyncTimesheetsInput>},
        TContext
      > => {
      return useMutation(getSyncPayrollTimesheetsMutationOptions(options));
    }

export const getSyncPayrollJournalUrl = () => {




  return `/api/payroll/sync/journal`
}

/**
 * @summary Push a posted pay run's journal to accounting
 */
export const syncPayrollJournal = async (syncJournalInput: SyncJournalInput, options?: RequestInit): Promise<PayrollSyncResult> => {

  return customFetch<PayrollSyncResult>(getSyncPayrollJournalUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncJournalInput,)
  }
);}




export const getSyncPayrollJournalMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPayrollJournal>>, TError,{data: BodyType<SyncJournalInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof syncPayrollJournal>>, TError,{data: BodyType<SyncJournalInput>}, TContext> => {

const mutationKey = ['syncPayrollJournal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncPayrollJournal>>, {data: BodyType<SyncJournalInput>}> = (props) => {
          const {data} = props ?? {};

          return  syncPayrollJournal(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncPayrollJournalMutationResult = NonNullable<Awaited<ReturnType<typeof syncPayrollJournal>>>
    export type SyncPayrollJournalMutationBody = BodyType<SyncJournalInput>
    export type SyncPayrollJournalMutationError = ErrorType<void>

    /**
 * @summary Push a posted pay run's journal to accounting
 */
export const useSyncPayrollJournal = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPayrollJournal>>, TError,{data: BodyType<SyncJournalInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof syncPayrollJournal>>,
        TError,
        {data: BodyType<SyncJournalInput>},
        TContext
      > => {
      return useMutation(getSyncPayrollJournalMutationOptions(options));
    }

export const getListPayRunsUrl = () => {




  return `/api/payroll/pay-runs`
}

/**
 * @summary List pay runs
 */
export const listPayRuns = async ( options?: RequestInit): Promise<PayRunList> => {

  return customFetch<PayRunList>(getListPayRunsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPayRunsQueryKey = () => {
    return [
    `/api/payroll/pay-runs`
    ] as const;
    }


export const getListPayRunsQueryOptions = <TData = Awaited<ReturnType<typeof listPayRuns>>, TError = ErrorType<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPayRuns>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPayRunsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPayRuns>>> = ({ signal }) => listPayRuns({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPayRuns>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPayRunsQueryResult = NonNullable<Awaited<ReturnType<typeof listPayRuns>>>
export type ListPayRunsQueryError = ErrorType<void>


/**
 * @summary List pay runs
 */

export function useListPayRuns<TData = Awaited<ReturnType<typeof listPayRuns>>, TError = ErrorType<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPayRuns>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPayRunsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreatePayRunUrl = () => {




  return `/api/payroll/pay-runs`
}

/**
 * @summary Create a draft pay run for a period
 */
export const createPayRun = async (createPayRunInput: CreatePayRunInput, options?: RequestInit): Promise<PayRun> => {

  return customFetch<PayRun>(getCreatePayRunUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPayRunInput,)
  }
);}




export const getCreatePayRunMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayRun>>, TError,{data: BodyType<CreatePayRunInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPayRun>>, TError,{data: BodyType<CreatePayRunInput>}, TContext> => {

const mutationKey = ['createPayRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPayRun>>, {data: BodyType<CreatePayRunInput>}> = (props) => {
          const {data} = props ?? {};

          return  createPayRun(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePayRunMutationResult = NonNullable<Awaited<ReturnType<typeof createPayRun>>>
    export type CreatePayRunMutationBody = BodyType<CreatePayRunInput>
    export type CreatePayRunMutationError = ErrorType<void>

    /**
 * @summary Create a draft pay run for a period
 */
export const useCreatePayRun = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPayRun>>, TError,{data: BodyType<CreatePayRunInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPayRun>>,
        TError,
        {data: BodyType<CreatePayRunInput>},
        TContext
      > => {
      return useMutation(getCreatePayRunMutationOptions(options));
    }

export const getGetPayRunUrl = (id: number,) => {




  return `/api/payroll/pay-runs/${id}`
}

/**
 * @summary Get a pay run with its payslips
 */
export const getPayRun = async (id: number, options?: RequestInit): Promise<PayRunDetail> => {

  return customFetch<PayRunDetail>(getGetPayRunUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPayRunQueryKey = (id: number,) => {
    return [
    `/api/payroll/pay-runs/${id}`
    ] as const;
    }


export const getGetPayRunQueryOptions = <TData = Awaited<ReturnType<typeof getPayRun>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPayRun>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPayRunQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPayRun>>> = ({ signal }) => getPayRun(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPayRun>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPayRunQueryResult = NonNullable<Awaited<ReturnType<typeof getPayRun>>>
export type GetPayRunQueryError = ErrorType<void>


/**
 * @summary Get a pay run with its payslips
 */

export function useGetPayRun<TData = Awaited<ReturnType<typeof getPayRun>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPayRun>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPayRunQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getPostPayRunUrl = (id: number,) => {




  return `/api/payroll/pay-runs/${id}/post`
}

/**
 * @summary Finalise (post) a pay run so the provider lodges STP
 */
export const postPayRun = async (id: number, options?: RequestInit): Promise<PayRun> => {

  return customFetch<PayRun>(getPostPayRunUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostPayRunMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPayRun>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postPayRun>>, TError,{id: number}, TContext> => {

const mutationKey = ['postPayRun'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPayRun>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postPayRun(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostPayRunMutationResult = NonNullable<Awaited<ReturnType<typeof postPayRun>>>

    export type PostPayRunMutationError = ErrorType<void>

    /**
 * @summary Finalise (post) a pay run so the provider lodges STP
 */
export const usePostPayRun = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPayRun>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postPayRun>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostPayRunMutationOptions(options));
    }

export const getListPayslipsUrl = (params?: ListPayslipsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/payroll/payslips?${stringifiedParams}` : `/api/payroll/payslips`
}

/**
 * @summary List payslips
 */
export const listPayslips = async (params?: ListPayslipsParams, options?: RequestInit): Promise<PayslipList> => {

  return customFetch<PayslipList>(getListPayslipsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPayslipsQueryKey = (params?: ListPayslipsParams,) => {
    return [
    `/api/payroll/payslips`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPayslipsQueryOptions = <TData = Awaited<ReturnType<typeof listPayslips>>, TError = ErrorType<void>>(params?: ListPayslipsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPayslips>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPayslipsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPayslips>>> = ({ signal }) => listPayslips(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPayslips>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPayslipsQueryResult = NonNullable<Awaited<ReturnType<typeof listPayslips>>>
export type ListPayslipsQueryError = ErrorType<void>


/**
 * @summary List payslips
 */

export function useListPayslips<TData = Awaited<ReturnType<typeof listPayslips>>, TError = ErrorType<void>>(
 params?: ListPayslipsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPayslips>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPayslipsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListLeaveBalancesUrl = (params?: ListLeaveBalancesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/payroll/leave-balances?${stringifiedParams}` : `/api/payroll/leave-balances`
}

/**
 * @summary List leave balances
 */
export const listLeaveBalances = async (params?: ListLeaveBalancesParams, options?: RequestInit): Promise<LeaveBalanceList> => {

  return customFetch<LeaveBalanceList>(getListLeaveBalancesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListLeaveBalancesQueryKey = (params?: ListLeaveBalancesParams,) => {
    return [
    `/api/payroll/leave-balances`, ...(params ? [params] : [])
    ] as const;
    }


export const getListLeaveBalancesQueryOptions = <TData = Awaited<ReturnType<typeof listLeaveBalances>>, TError = ErrorType<void>>(params?: ListLeaveBalancesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listLeaveBalances>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLeaveBalancesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLeaveBalances>>> = ({ signal }) => listLeaveBalances(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLeaveBalances>>, TError, TData> & { queryKey: QueryKey }
}

export type ListLeaveBalancesQueryResult = NonNullable<Awaited<ReturnType<typeof listLeaveBalances>>>
export type ListLeaveBalancesQueryError = ErrorType<void>


/**
 * @summary List leave balances
 */

export function useListLeaveBalances<TData = Awaited<ReturnType<typeof listLeaveBalances>>, TError = ErrorType<void>>(
 params?: ListLeaveBalancesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listLeaveBalances>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListLeaveBalancesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







